# Generated by Django 4.1.6 on 2024-03-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupLoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', upload_to='profile_pictures/'),
        ),
    ]
